name: test
on: 
  push:
    branches:
      - master
      - v2
  pull_request:
    branches:
      - master
      - v2

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.21.x, 1.22.x]
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Install libpcsc
      run: sudo apt-get install -y libpcsclite-dev pcscd pcsc-tools
    - name: Test
      run: "go test -C v2 ./..."
  build-windows:
    strategy:
      matrix:
        go-version: [1.21.x, 1.22.x]
    name: Windows
    runs-on: windows-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Test
      run: "go build -C v2 ./..."
      env:
        CGO_ENABLED: 0
